//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выпускаемый продукт.
    /// </summary>
    // *** Start programmer edit section *** (ГотовыйПродукт CustomAttributes)

    // *** End programmer edit section *** (ГотовыйПродукт CustomAttributes)
    [BusinessServer("IIS.АСУ_Кондитерская.ГотовыйПродуктBS, АСУ_Кондитерская.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Выпускаемый продукт")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ГотовыйПродуктE", new string[] {
            "Продукт as \'Продукт\'",
            "Продукт.Наименование as \'Продукт\'",
            "Выпущено as \'Выпущено\'",
            "НаСкладе as \'На складе\'",
            "ДатаИзг as \'Дата изготовления\'",
            "Цех"}, Hidden=new string[] {
            "Продукт.Наименование",
            "Цех"})]
    [MasterViewDefineAttribute("ГотовыйПродуктE", "Продукт", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ГотовыйПродукт : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаИзг = System.DateTime.Now;
        
        private int fВыпущено;
        
        private int fНаСкладе;
        
        private IIS.АСУ_Кондитерская.Продукт fПродукт;
        
        private IIS.АСУ_Кондитерская.Цех fЦех;
        
        // *** Start programmer edit section *** (ГотовыйПродукт CustomMembers)

        // *** End programmer edit section *** (ГотовыйПродукт CustomMembers)

        
        /// <summary>
        /// ДатаИзг.
        /// </summary>
        // *** Start programmer edit section *** (ГотовыйПродукт.ДатаИзг CustomAttributes)

        // *** End programmer edit section *** (ГотовыйПродукт.ДатаИзг CustomAttributes)
        public virtual System.DateTime ДатаИзг
        {
            get
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.ДатаИзг Get start)

                // *** End programmer edit section *** (ГотовыйПродукт.ДатаИзг Get start)
                System.DateTime result = this.fДатаИзг;
                // *** Start programmer edit section *** (ГотовыйПродукт.ДатаИзг Get end)

                // *** End programmer edit section *** (ГотовыйПродукт.ДатаИзг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.ДатаИзг Set start)

                // *** End programmer edit section *** (ГотовыйПродукт.ДатаИзг Set start)
                this.fДатаИзг = value;
                // *** Start programmer edit section *** (ГотовыйПродукт.ДатаИзг Set end)

                // *** End programmer edit section *** (ГотовыйПродукт.ДатаИзг Set end)
            }
        }
        
        /// <summary>
        /// Выпущено.
        /// </summary>
        // *** Start programmer edit section *** (ГотовыйПродукт.Выпущено CustomAttributes)

        // *** End programmer edit section *** (ГотовыйПродукт.Выпущено CustomAttributes)
        public virtual int Выпущено
        {
            get
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Выпущено Get start)

                // *** End programmer edit section *** (ГотовыйПродукт.Выпущено Get start)
                int result = this.fВыпущено;
                // *** Start programmer edit section *** (ГотовыйПродукт.Выпущено Get end)

                // *** End programmer edit section *** (ГотовыйПродукт.Выпущено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Выпущено Set start)
                if (value <= 0)
                    throw new ArgumentOutOfRangeException();
                // *** End programmer edit section *** (ГотовыйПродукт.Выпущено Set start)
                this.fВыпущено = value;
                // *** Start programmer edit section *** (ГотовыйПродукт.Выпущено Set end)

                // *** End programmer edit section *** (ГотовыйПродукт.Выпущено Set end)
            }
        }
        
        /// <summary>
        /// НаСкладе.
        /// </summary>
        // *** Start programmer edit section *** (ГотовыйПродукт.НаСкладе CustomAttributes)

        // *** End programmer edit section *** (ГотовыйПродукт.НаСкладе CustomAttributes)
        public virtual int НаСкладе
        {
            get
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.НаСкладе Get start)

                // *** End programmer edit section *** (ГотовыйПродукт.НаСкладе Get start)
                int result = this.fНаСкладе;
                // *** Start programmer edit section *** (ГотовыйПродукт.НаСкладе Get end)

                // *** End programmer edit section *** (ГотовыйПродукт.НаСкладе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.НаСкладе Set start)
                if (value <= 0)
                    throw new ArgumentOutOfRangeException();
                // *** End programmer edit section *** (ГотовыйПродукт.НаСкладе Set start)
                this.fНаСкладе = value;
                // *** Start programmer edit section *** (ГотовыйПродукт.НаСкладе Set end)

                // *** End programmer edit section *** (ГотовыйПродукт.НаСкладе Set end)
            }
        }
        
        /// <summary>
        /// Выпускаемый продукт.
        /// </summary>
        // *** Start programmer edit section *** (ГотовыйПродукт.Продукт CustomAttributes)

        // *** End programmer edit section *** (ГотовыйПродукт.Продукт CustomAttributes)
        [PropertyStorage(new string[] {
                "Продукт"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Продукт Продукт
        {
            get
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Продукт Get start)

                // *** End programmer edit section *** (ГотовыйПродукт.Продукт Get start)
                IIS.АСУ_Кондитерская.Продукт result = this.fПродукт;
                // *** Start programmer edit section *** (ГотовыйПродукт.Продукт Get end)

                // *** End programmer edit section *** (ГотовыйПродукт.Продукт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Продукт Set start)

                // *** End programmer edit section *** (ГотовыйПродукт.Продукт Set start)
                this.fПродукт = value;
                // *** Start programmer edit section *** (ГотовыйПродукт.Продукт Set end)

                // *** End programmer edit section *** (ГотовыйПродукт.Продукт Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Кондитерская.Цех.
        /// </summary>
        // *** Start programmer edit section *** (ГотовыйПродукт.Цех CustomAttributes)

        // *** End programmer edit section *** (ГотовыйПродукт.Цех CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Цех"})]
        public virtual IIS.АСУ_Кондитерская.Цех Цех
        {
            get
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Цех Get start)

                // *** End programmer edit section *** (ГотовыйПродукт.Цех Get start)
                IIS.АСУ_Кондитерская.Цех result = this.fЦех;
                // *** Start programmer edit section *** (ГотовыйПродукт.Цех Get end)

                // *** End programmer edit section *** (ГотовыйПродукт.Цех Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотовыйПродукт.Цех Set start)

                // *** End programmer edit section *** (ГотовыйПродукт.Цех Set start)
                this.fЦех = value;
                // *** Start programmer edit section *** (ГотовыйПродукт.Цех Set end)

                // *** End programmer edit section *** (ГотовыйПродукт.Цех Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГотовыйПродуктE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГотовыйПродуктE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГотовыйПродуктE", typeof(IIS.АСУ_Кондитерская.ГотовыйПродукт));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ГотовыйПродукт.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГотовыйПродукт CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГотовыйПродукт CustomAttributes)
    public class DetailArrayOfГотовыйПродукт : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт members)

        // *** End programmer edit section *** (IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ГотовыйПродукт by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ГотовыйПродукт.
        /// </summary>
        public DetailArrayOfГотовыйПродукт(IIS.АСУ_Кондитерская.Цех fЦех) : 
                base(typeof(ГотовыйПродукт), ((ICSSoft.STORMNET.DataObject)(fЦех)))
        {
        }
        
        public IIS.АСУ_Кондитерская.ГотовыйПродукт this[int index]
        {
            get
            {
                return ((IIS.АСУ_Кондитерская.ГотовыйПродукт)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Кондитерская.ГотовыйПродукт dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
