//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [BusinessServer("IIS.АСУ_Кондитерская.ЗаказBS, АСУ_Кондитерская.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ЗаказE", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ТорговаяТочка as \'Торговая точка\'",
            "ТорговаяТочка.Адрес"}, Hidden=new string[] {
            "ТорговаяТочка.Адрес"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "ТорговаяТочка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("ЗаказL", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ТорговаяТочка.Адрес as \'Адрес торговой точки\'"})]
    public class Заказ : IIS.АСУ_Кондитерская.Документ
    {
        
        private IIS.АСУ_Кондитерская.СостояниеЗаказа fСостояние;
        
        private System.DateTime fДатаПоступления;
        
        private IIS.АСУ_Кондитерская.ТорговаяТочка fТорговаяТочка;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Состояние CustomAttributes)

        // *** End programmer edit section *** (Заказ.Состояние CustomAttributes)
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.СостояниеЗаказа Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Состояние Get start)

                // *** End programmer edit section *** (Заказ.Состояние Get start)
                IIS.АСУ_Кондитерская.СостояниеЗаказа result = this.fСостояние;
                // *** Start programmer edit section *** (Заказ.Состояние Get end)

                // *** End programmer edit section *** (Заказ.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Состояние Set start)

                // *** End programmer edit section *** (Заказ.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Заказ.Состояние Set end)

                // *** End programmer edit section *** (Заказ.Состояние Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаПоступления CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаПоступления CustomAttributes)
        public virtual System.DateTime ДатаПоступления
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаПоступления Get start)

                // *** End programmer edit section *** (Заказ.ДатаПоступления Get start)
                System.DateTime result = this.fДатаПоступления;
                // *** Start programmer edit section *** (Заказ.ДатаПоступления Get end)

                // *** End programmer edit section *** (Заказ.ДатаПоступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаПоступления Set start)

                // *** End programmer edit section *** (Заказ.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                // *** Start programmer edit section *** (Заказ.ДатаПоступления Set end)

                // *** End programmer edit section *** (Заказ.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ТорговаяТочка CustomAttributes)

        // *** End programmer edit section *** (Заказ.ТорговаяТочка CustomAttributes)
        [PropertyStorage(new string[] {
                "ТорговаяТочка"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.ТорговаяТочка ТорговаяТочка
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ТорговаяТочка Get start)

                // *** End programmer edit section *** (Заказ.ТорговаяТочка Get start)
                IIS.АСУ_Кондитерская.ТорговаяТочка result = this.fТорговаяТочка;
                // *** Start programmer edit section *** (Заказ.ТорговаяТочка Get end)

                // *** End programmer edit section *** (Заказ.ТорговаяТочка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ТорговаяТочка Set start)

                // *** End programmer edit section *** (Заказ.ТорговаяТочка Set start)
                this.fТорговаяТочка = value;
                // *** Start programmer edit section *** (Заказ.ТорговаяТочка Set end)

                // *** End programmer edit section *** (Заказ.ТорговаяТочка Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.АСУ_Кондитерская.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.АСУ_Кондитерская.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.АСУ_Кондитерская.Заказ));
                }
            }
        }
    }
}
