//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Индивидуальный заказ.
    /// </summary>
    // *** Start programmer edit section *** (ИндивидуальныйЗаказ CustomAttributes)

    // *** End programmer edit section *** (ИндивидуальныйЗаказ CustomAttributes)
    [BusinessServer("IIS.АСУ_Кондитерская.ИндЗаказBS, АСУ_Кондитерская.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Индивидуальный заказ")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ИндивидуальныйЗаказE", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "ФИОЗаказчика as \'ФИО заказчика\'",
            "СрокБрони as \'Срок брони (дней)\'",
            "ДатаПоступления as \'Дата поступления\'",
            "Стоимость as \'Стоимость\'",
            "ТорговаяТочка as \'Торговая точка\'",
            "ТорговаяТочка.Адрес"}, Hidden=new string[] {
            "ТорговаяТочка.Адрес"})]
    [AssociatedDetailViewAttribute("ИндивидуальныйЗаказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ИндивидуальныйЗаказE", "ТорговаяТочка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("ИндивидуальныйЗаказL", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "ФИОЗаказчика as \'ФИО заказчика\'",
            "СрокБрони as \'Срок брони (дней)\'",
            "ДатаПоступления as \'Дата поступления\'",
            "Стоимость as \'Стоимость\'",
            "ТорговаяТочка.Адрес as \'Адрес торговой точки\'"})]
    public class ИндивидуальныйЗаказ : IIS.АСУ_Кондитерская.Заказ
    {
        
        private string fФИОЗаказчика;
        
        private int fСрокБрони;
        
        // *** Start programmer edit section *** (ИндивидуальныйЗаказ CustomMembers)

        // *** End programmer edit section *** (ИндивидуальныйЗаказ CustomMembers)

        
        /// <summary>
        /// ФИОЗаказчика.
        /// </summary>
        // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика CustomAttributes)

        // *** End programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИОЗаказчика
        {
            get
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Get start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Get start)
                string result = this.fФИОЗаказчика;
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Get end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Set start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Set start)
                this.fФИОЗаказчика = value;
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Set end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ФИОЗаказчика Set end)
            }
        }
        
        /// <summary>
        /// СрокБрони.
        /// </summary>
        // *** Start programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони CustomAttributes)

        // *** End programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони CustomAttributes)
        [NotNull()]
        public virtual int СрокБрони
        {
            get
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Get start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Get start)
                int result = this.fСрокБрони;
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Get end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Set start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Set start)
                this.fСрокБрони = value;
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Set end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.СрокБрони Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ИндивидуальныйЗаказ.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ИндивидуальныйЗаказ.Стоимость CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.Стоимость Get)
                double sum = 0;
                IDataService ds = DataServiceProvider.DataService;
                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(СтрокаЗаказа), "СтрокаЗаказаE");
                SQLWhereLanguageDef ld = SQLWhereLanguageDef.LanguageDef;

                lcs.InitDataCopy = false;
                lcs.LimitFunction = ld.GetFunction(ld.funcEQ,
                    new VariableDef(ld.GuidType, Information.ExtractPropertyPath<СтрокаЗаказа>(x => x.Заказ)), this.__PrimaryKey);
                var details = ds.LoadObjects(lcs);

                foreach(var det in details)
                {
                    ds.LoadObject(((СтрокаЗаказа)det).Продукт);
                    sum += ((СтрокаЗаказа)det).Продукт.Цена * ((СтрокаЗаказа)det).Количество;
                }
               
                return sum;
                // *** End programmer edit section *** (ИндивидуальныйЗаказ.Стоимость Get)
            }
            set
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.Стоимость Set)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.Стоимость Set)
            }
        }
        
        /// <summary>
        /// Индивидуальный заказ.
        /// </summary>
        // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка CustomAttributes)

        // *** End programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка CustomAttributes)
        [TypeUsage(typeof(IIS.АСУ_Кондитерская.ТорговаяТочка))]
        [PropertyStorage(new string[] {
                "ТорговаяТочка"})]
        public override IIS.АСУ_Кондитерская.ТорговаяТочка ТорговаяТочка
        {
            get
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Get start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Get start)
                IIS.АСУ_Кондитерская.ТорговаяТочка result = ((IIS.АСУ_Кондитерская.ТорговаяТочка)(base.ТорговаяТочка));
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Get end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Set start)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Set start)
                base.ТорговаяТочка = ((IIS.АСУ_Кондитерская.ТорговаяТочка)(value));
                // *** Start programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Set end)

                // *** End programmer edit section *** (ИндивидуальныйЗаказ.ТорговаяТочка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИндивидуальныйЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИндивидуальныйЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИндивидуальныйЗаказE", typeof(IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ));
                }
            }
            
            /// <summary>
            /// "ИндивидуальныйЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИндивидуальныйЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИндивидуальныйЗаказL", typeof(IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ));
                }
            }
        }
    }
}
