//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПродуктКПразднику.
    /// </summary>
    // *** Start programmer edit section *** (ПродуктКПразднику CustomAttributes)

    // *** End programmer edit section *** (ПродуктКПразднику CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродуктКПраздникуE", new string[] {
            "Продукт as \'Продукт\'",
            "Продукт.Наименование"}, Hidden=new string[] {
            "Продукт.Наименование"})]
    [MasterViewDefineAttribute("ПродуктКПраздникуE", "Продукт", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Наименование")]
    public class ПродуктКПразднику : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.АСУ_Кондитерская.Продукт fПродукт;
        
        private IIS.АСУ_Кондитерская.Праздник fПраздник;
        
        // *** Start programmer edit section *** (ПродуктКПразднику CustomMembers)

        // *** End programmer edit section *** (ПродуктКПразднику CustomMembers)

        
        /// <summary>
        /// ПродуктКПразднику.
        /// </summary>
        // *** Start programmer edit section *** (ПродуктКПразднику.Продукт CustomAttributes)

        // *** End programmer edit section *** (ПродуктКПразднику.Продукт CustomAttributes)
        [PropertyStorage(new string[] {
                "Продукт"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Продукт Продукт
        {
            get
            {
                // *** Start programmer edit section *** (ПродуктКПразднику.Продукт Get start)

                // *** End programmer edit section *** (ПродуктКПразднику.Продукт Get start)
                IIS.АСУ_Кондитерская.Продукт result = this.fПродукт;
                // *** Start programmer edit section *** (ПродуктКПразднику.Продукт Get end)

                // *** End programmer edit section *** (ПродуктКПразднику.Продукт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПродуктКПразднику.Продукт Set start)

                // *** End programmer edit section *** (ПродуктКПразднику.Продукт Set start)
                this.fПродукт = value;
                // *** Start programmer edit section *** (ПродуктКПразднику.Продукт Set end)

                // *** End programmer edit section *** (ПродуктКПразднику.Продукт Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_Кондитерская.Праздник.
        /// </summary>
        // *** Start programmer edit section *** (ПродуктКПразднику.Праздник CustomAttributes)

        // *** End programmer edit section *** (ПродуктКПразднику.Праздник CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Праздник"})]
        public virtual IIS.АСУ_Кондитерская.Праздник Праздник
        {
            get
            {
                // *** Start programmer edit section *** (ПродуктКПразднику.Праздник Get start)

                // *** End programmer edit section *** (ПродуктКПразднику.Праздник Get start)
                IIS.АСУ_Кондитерская.Праздник result = this.fПраздник;
                // *** Start programmer edit section *** (ПродуктКПразднику.Праздник Get end)

                // *** End programmer edit section *** (ПродуктКПразднику.Праздник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПродуктКПразднику.Праздник Set start)

                // *** End programmer edit section *** (ПродуктКПразднику.Праздник Set start)
                this.fПраздник = value;
                // *** Start programmer edit section *** (ПродуктКПразднику.Праздник Set end)

                // *** End programmer edit section *** (ПродуктКПразднику.Праздник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродуктКПраздникуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродуктКПраздникуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродуктКПраздникуE", typeof(IIS.АСУ_Кондитерская.ПродуктКПразднику));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПродуктКПразднику.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПродуктКПразднику CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПродуктКПразднику CustomAttributes)
    public class DetailArrayOfПродуктКПразднику : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_Кондитерская.DetailArrayOfПродуктКПразднику members)

        // *** End programmer edit section *** (IIS.АСУ_Кондитерская.DetailArrayOfПродуктКПразднику members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПродуктКПразднику by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПродуктКПразднику.
        /// </summary>
        public DetailArrayOfПродуктКПразднику(IIS.АСУ_Кондитерская.Праздник fПраздник) : 
                base(typeof(ПродуктКПразднику), ((ICSSoft.STORMNET.DataObject)(fПраздник)))
        {
        }
        
        public IIS.АСУ_Кондитерская.ПродуктКПразднику this[int index]
        {
            get
            {
                return ((IIS.АСУ_Кондитерская.ПродуктКПразднику)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_Кондитерская.ПродуктКПразднику dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
