//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продавец.
    /// </summary>
    // *** Start programmer edit section *** (Продавец CustomAttributes)

    // *** End programmer edit section *** (Продавец CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродавецE", new string[] {
            "ТабельныйНомер as \'Табельный номер\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Логин as \'Логин\'",
            "Телефон as \'Телефон\'",
            "ТорговаяТочка as \'Торговая точка\'",
            "ТорговаяТочка.Адрес as \'Адрес\'"}, Hidden=new string[] {
            "ТорговаяТочка.Адрес"})]
    [MasterViewDefineAttribute("ПродавецE", "ТорговаяТочка", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Адрес")]
    [View("ПродавецL", new string[] {
            "ТабельныйНомер as \'Табельный номер\'",
            "ФИО as \'ФИО\'",
            "Логин as \'Логин\'",
            "Телефон as \'Телефон\'",
            "ТорговаяТочка.Адрес as \'Адрес\'",
            "Фамилия",
            "Имя",
            "Отчество"}, Hidden=new string[] {
            "Фамилия",
            "Имя",
            "Отчество"})]
    public class Продавец : IIS.АСУ_Кондитерская.Сотрудник
    {
        
        private IIS.АСУ_Кондитерская.ТорговаяТочка fТорговаяТочка;
        
        // *** Start programmer edit section *** (Продавец CustomMembers)

        // *** End programmer edit section *** (Продавец CustomMembers)

        
        /// <summary>
        /// Продавец.
        /// </summary>
        // *** Start programmer edit section *** (Продавец.ТорговаяТочка CustomAttributes)

        // *** End programmer edit section *** (Продавец.ТорговаяТочка CustomAttributes)
        [PropertyStorage(new string[] {
                "ТорговаяТочка"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.ТорговаяТочка ТорговаяТочка
        {
            get
            {
                // *** Start programmer edit section *** (Продавец.ТорговаяТочка Get start)

                // *** End programmer edit section *** (Продавец.ТорговаяТочка Get start)
                IIS.АСУ_Кондитерская.ТорговаяТочка result = this.fТорговаяТочка;
                // *** Start programmer edit section *** (Продавец.ТорговаяТочка Get end)

                // *** End programmer edit section *** (Продавец.ТорговаяТочка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продавец.ТорговаяТочка Set start)

                // *** End programmer edit section *** (Продавец.ТорговаяТочка Set start)
                this.fТорговаяТочка = value;
                // *** Start programmer edit section *** (Продавец.ТорговаяТочка Set end)

                // *** End programmer edit section *** (Продавец.ТорговаяТочка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродавецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродавецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродавецE", typeof(IIS.АСУ_Кондитерская.Продавец));
                }
            }
            
            /// <summary>
            /// "ПродавецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродавецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродавецL", typeof(IIS.АСУ_Кондитерская.Продавец));
                }
            }
        }
    }
}
