//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Работник цеха.
    /// </summary>
    // *** Start programmer edit section *** (РаботникЦеха CustomAttributes)

    // *** End programmer edit section *** (РаботникЦеха CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [Caption("Работник цеха")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РаботникЦехаE", new string[] {
            "ТабельныйНомер as \'Табельный номер\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Логин as \'Логин\'",
            "Телефон as \'Телефон\'",
            "ФИО as \'ФИО\'",
            "Цех as \'Цех\'",
            "Цех.Адрес"}, Hidden=new string[] {
            "ФИО",
            "Цех.Адрес"})]
    [MasterViewDefineAttribute("РаботникЦехаE", "Цех", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Адрес")]
    [View("РаботникЦехаL", new string[] {
            "ТабельныйНомер as \'Табельный номер\'",
            "ФИО as \'ФИО\'",
            "Логин as \'Логин\'",
            "Телефон as \'Телефон\'",
            "Цех.Адрес as \'Цех\'",
            "Фамилия",
            "Имя",
            "Отчество"}, Hidden=new string[] {
            "Фамилия",
            "Имя",
            "Отчество"})]
    public class РаботникЦеха : IIS.АСУ_Кондитерская.Сотрудник
    {
        
        private IIS.АСУ_Кондитерская.Цех fЦех;
        
        // *** Start programmer edit section *** (РаботникЦеха CustomMembers)

        // *** End programmer edit section *** (РаботникЦеха CustomMembers)

        
        /// <summary>
        /// Работник цеха.
        /// </summary>
        // *** Start programmer edit section *** (РаботникЦеха.Цех CustomAttributes)

        // *** End programmer edit section *** (РаботникЦеха.Цех CustomAttributes)
        [PropertyStorage(new string[] {
                "Цех"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Цех Цех
        {
            get
            {
                // *** Start programmer edit section *** (РаботникЦеха.Цех Get start)

                // *** End programmer edit section *** (РаботникЦеха.Цех Get start)
                IIS.АСУ_Кондитерская.Цех result = this.fЦех;
                // *** Start programmer edit section *** (РаботникЦеха.Цех Get end)

                // *** End programmer edit section *** (РаботникЦеха.Цех Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаботникЦеха.Цех Set start)

                // *** End programmer edit section *** (РаботникЦеха.Цех Set start)
                this.fЦех = value;
                // *** Start programmer edit section *** (РаботникЦеха.Цех Set end)

                // *** End programmer edit section *** (РаботникЦеха.Цех Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РаботникЦехаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботникЦехаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботникЦехаE", typeof(IIS.АСУ_Кондитерская.РаботникЦеха));
                }
            }
            
            /// <summary>
            /// "РаботникЦехаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботникЦехаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботникЦехаL", typeof(IIS.АСУ_Кондитерская.РаботникЦеха));
                }
            }
        }
    }
}
