//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние заказа.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеЗаказа CustomAttributes)

    // *** End programmer edit section *** (СостояниеЗаказа CustomAttributes)
    public enum СостояниеЗаказа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЗаказа.Новый CustomAttributes)

        // *** End programmer edit section *** (СостояниеЗаказа.Новый CustomAttributes)
        Новый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЗаказа.Выполненный CustomAttributes)

        // *** End programmer edit section *** (СостояниеЗаказа.Выполненный CustomAttributes)
        Выполненный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЗаказа.Отмененный CustomAttributes)

        // *** End programmer edit section *** (СостояниеЗаказа.Отмененный CustomAttributes)
        Отмененный,
    }
}
