//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние чека.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеЧека CustomAttributes)

    // *** End programmer edit section *** (СостояниеЧека CustomAttributes)
    public enum СостояниеЧека
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Открытый CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Открытый CustomAttributes)
        Открытый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Закрытый CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Закрытый CustomAttributes)
        Закрытый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Отмененный CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Отмененный CustomAttributes)
        Отмененный,
    }
}
