//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние чека.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеЧека CustomAttributes)

    // *** End programmer edit section *** (СостояниеЧека CustomAttributes)
    public enum СостояниеЧека
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Открытый CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Открытый CustomAttributes)
        Открытый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Закрытый CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Закрытый CustomAttributes)
        Закрытый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЧека.Отмененный CustomAttributes)

        // *** End programmer edit section *** (СостояниеЧека.Отмененный CustomAttributes)
        Отмененный,
    }
}
