//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус продукта.
    /// </summary>
    // *** Start programmer edit section *** (СтатусПродукта CustomAttributes)

    // *** End programmer edit section *** (СтатусПродукта CustomAttributes)
    public enum СтатусПродукта
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусПродукта.СнятСПродажи CustomAttributes)

        // *** End programmer edit section *** (СтатусПродукта.СнятСПродажи CustomAttributes)
        [Caption("Снят с продажи")]
        СнятСПродажи,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусПродукта.ВПродаже CustomAttributes)

        // *** End programmer edit section *** (СтатусПродукта.ВПродаже CustomAttributes)
        [Caption("В продаже")]
        ВПродаже,
    }
}
