//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Торговая точка.
    /// </summary>
    // *** Start programmer edit section *** (ТорговаяТочка CustomAttributes)

    // *** End programmer edit section *** (ТорговаяТочка CustomAttributes)
    [AutoAltered()]
    [Caption("Торговая точка")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ТорговаяТочкаE", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "Цех as \'Цех\'",
            "Цех.Адрес"}, Hidden=new string[] {
            "Цех.Адрес"})]
    [AssociatedDetailViewAttribute("ТорговаяТочкаE", "ПродуктНаПродажу", "ПродуктНаПродажуE", true, "", "Продукты на продажу", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ТорговаяТочкаE", "Цех", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Адрес")]
    [View("ТорговаяТочкаL", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "КоэффБезотх as \'Безотходность (%)\'"})]
    [AssociatedDetailViewAttribute("ТорговаяТочкаL", "ПродуктНаПродажу", "ПродуктНаПродажуE", true, "", "Продукт на продажу", true, new string[] {
            ""})]
    public class ТорговаяТочка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fАдрес;
        
        private IIS.АСУ_Кондитерская.Цех fЦех;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу fПродуктНаПродажу;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfУничтоженныйПродукт fУничтоженныйПродукт;
        
        // *** Start programmer edit section *** (ТорговаяТочка CustomMembers)

        // *** End programmer edit section *** (ТорговаяТочка CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.Номер CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.Адрес CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.Адрес CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Set end)
            }
        }
        
        /// <summary>
        /// КоэффБезотх.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double КоэффБезотх
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх Get)
                IDataService ds = DataServiceProvider.DataService;
                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(УничтоженныйПродукт),"УничтоженныйПродуктE");
                SQLWhereLanguageDef ld = SQLWhereLanguageDef.LanguageDef;
                lcs.LimitFunction = ld.GetFunction(ld.funcEQ, 
                    new VariableDef(ld.GuidType, Information.ExtractPropertyPath<УничтоженныйПродукт>(r => r.ТорговаяТочка)), 
                    this.__PrimaryKey);
                var dobjs = ds.LoadObjects(lcs);

                int count_util = 0;
                foreach(УничтоженныйПродукт util in dobjs)
                {
                    count_util += util.Количество;
                }

                lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Заказ), "ЗаказE");
                lcs.LimitFunction = ld.GetFunction(ld.funcAND,
                    ld.GetFunction(ld.funcEQ,
                        new VariableDef(ld.StringType, Information.ExtractPropertyPath<Заказ>(r => r.Состояние)),
                        "Выполненный"),
                    ld.GetFunction(ld.funcEQ,
                        new VariableDef(ld.GuidType, Information.ExtractPropertyPath<Заказ>(r => r.ТорговаяТочка)),
                        this.__PrimaryKey));
                var orders = ds.LoadObjects(lcs);

                int count_total = 0;
                foreach (Заказ order in orders)
                {
                    count_total += order.СтрокаЗаказа.CountProduct();
                }
                if (count_total != 0)
                    return 100-Math.Round((1.0)*count_util / count_total * 100);
                else
                    return -1;
                // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх Get)
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх Set)

                // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх Set)
            }
        }
        
        /// <summary>
        /// Торговая точка.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.Цех CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.Цех CustomAttributes)
        [PropertyStorage(new string[] {
                "Цех"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Цех Цех
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Get start)
                IIS.АСУ_Кондитерская.Цех result = this.fЦех;
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Set start)
                this.fЦех = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Set end)
            }
        }
        
        /// <summary>
        /// Торговая точка.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу ПродуктНаПродажу
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get start)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get start)
                if ((this.fПродуктНаПродажу == null))
                {
                    this.fПродуктНаПродажу = new IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу result = this.fПродуктНаПродажу;
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get end)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set start)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set start)
                this.fПродуктНаПродажу = value;
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set end)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set end)
            }
        }
        
        /// <summary>
        /// Торговая точка.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfУничтоженныйПродукт УничтоженныйПродукт
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Get start)

                // *** End programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Get start)
                if ((this.fУничтоженныйПродукт == null))
                {
                    this.fУничтоженныйПродукт = new IIS.АСУ_Кондитерская.DetailArrayOfУничтоженныйПродукт(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfУничтоженныйПродукт result = this.fУничтоженныйПродукт;
                // *** Start programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Get end)

                // *** End programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Set start)

                // *** End programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Set start)
                this.fУничтоженныйПродукт = value;
                // *** Start programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Set end)

                // *** End programmer edit section *** (ТорговаяТочка.УничтоженныйПродукт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТорговаяТочкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТорговаяТочкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТорговаяТочкаE", typeof(IIS.АСУ_Кондитерская.ТорговаяТочка));
                }
            }
            
            /// <summary>
            /// "ТорговаяТочкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТорговаяТочкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТорговаяТочкаL", typeof(IIS.АСУ_Кондитерская.ТорговаяТочка));
                }
            }
        }
    }
}
