//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    using ICSSoft.STORMNET.Windows.Forms;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Торговая точка.
    /// </summary>
    // *** Start programmer edit section *** (ТорговаяТочка CustomAttributes)

    // *** End programmer edit section *** (ТорговаяТочка CustomAttributes)
    [AutoAltered()]
    [Caption("Торговая точка")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ТорговаяТочкаE", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "Цех as \'Цех\'",
            "Цех.Адрес"}, Hidden=new string[] {
            "Цех.Адрес"})]
    [AssociatedDetailViewAttribute("ТорговаяТочкаE", "ПродуктНаПродажу", "ПродуктНаПродажуE", true, "", "Продукты на продажу", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ТорговаяТочкаE", "Цех", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Адрес")]
    [View("ТорговаяТочкаL", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'",
            "КоэффБезотх as \'Безотходность (%)\'"})]
    [AssociatedDetailViewAttribute("ТорговаяТочкаL", "ПродуктНаПродажу", "ПродуктНаПродажуE", true, "", "Продукт на продажу", true, new string[] {
            ""})]
    public class ТорговаяТочка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fАдрес;
        
        private IIS.АСУ_Кондитерская.Цех fЦех;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу fПродуктНаПродажу;
        
        // *** Start programmer edit section *** (ТорговаяТочка CustomMembers)

        // *** End programmer edit section *** (ТорговаяТочка CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.Номер CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Номер Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Номер Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.Адрес CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.Адрес CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Адрес Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Адрес Set end)
            }
        }
        
        /// <summary>
        /// КоэффБезотх.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double КоэффБезотх
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх Get)

                IDataService ds = DataServiceProvider.DataService;
                View view = IIS.АСУ_Кондитерская.ПродуктНаПродажу.Views.ПродуктНаПродажуE;
                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(ПродуктНаПродажу), view);
                ExternalLangDef ld = ExternalLangDef.LanguageDef;
                
                var dvd = new DetailVariableDef(ld.GetObjectType("Details"), "ПродуктНаПродажу", view, "ТорговаяТочка", null);
                var dvd2 = new DetailVariableDef(ld.GetObjectType("Details"), "ПродуктНаПродажу", view, "ТорговаяТочка", null);

                Function поступило_lim = ld.GetFunction(ld.funcSumWithLimit,
                            dvd2, new VariableDef(ld.NumericType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.Поступило)),
                            ld.GetFunction(ld.funcEQ,
                                new VariableDef(ld.GuidType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.ТорговаяТочка)),
                                this.__PrimaryKey));
                Function уничтожено_lim = ld.GetFunction(ld.funcSumWithLimit,
                            dvd, new VariableDef(ld.NumericType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.Осталось)),
                            ld.GetFunction(ld.funcAND,
                                ld.GetFunction(ld.funcEQ,
                                    new VariableDef(ld.GuidType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.ТорговаяТочка)),
                                    this.__PrimaryKey),
                                ld.GetFunction(ld.funcNotIsNull,
                                    new VariableDef(ld.DateTimeType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.ДатаУничтожения)))));

                Function lf = ld.GetFunction(ld.funcG, 
                    new VariableDef(ld.NumericType, Information.ExtractPropertyPath<ПродуктНаПродажу>(r => r.Поступило)),
                    //ld.GetFunction(ld.funcSub, уничтожено_lim, поступило_lim));
                    8);


                lcs.LimitFunction = lf;
                var dobjs = ds.LoadObjects(lcs);                
                
                return -1;
                // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх Get)
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.КоэффБезотх Set)

                // *** End programmer edit section *** (ТорговаяТочка.КоэффБезотх Set)
            }
        }

/// <summary>
/// Торговая точка.
/// </summary>
// *** Start programmer edit section *** (ТорговаяТочка.Цех CustomAttributes)

// *** End programmer edit section *** (ТорговаяТочка.Цех CustomAttributes)
[PropertyStorage(new string[] {
                "Цех"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Цех Цех
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Get start)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Get start)
                IIS.АСУ_Кондитерская.Цех result = this.fЦех;
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Get end)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Set start)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Set start)
                this.fЦех = value;
                // *** Start programmer edit section *** (ТорговаяТочка.Цех Set end)

                // *** End programmer edit section *** (ТорговаяТочка.Цех Set end)
            }
        }
        
        /// <summary>
        /// Торговая точка.
        /// </summary>
        // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу CustomAttributes)

        // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу ПродуктНаПродажу
        {
            get
            {
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get start)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get start)
                if ((this.fПродуктНаПродажу == null))
                {
                    this.fПродуктНаПродажу = new IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfПродуктНаПродажу result = this.fПродуктНаПродажу;
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get end)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set start)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set start)
                this.fПродуктНаПродажу = value;
                // *** Start programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set end)

                // *** End programmer edit section *** (ТорговаяТочка.ПродуктНаПродажу Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТорговаяТочкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТорговаяТочкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТорговаяТочкаE", typeof(IIS.АСУ_Кондитерская.ТорговаяТочка));
                }
            }
            
            /// <summary>
            /// "ТорговаяТочкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТорговаяТочкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТорговаяТочкаL", typeof(IIS.АСУ_Кондитерская.ТорговаяТочка));
                }
            }
        }
    }
}
