//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Цех.
    /// </summary>
    // *** Start programmer edit section *** (Цех CustomAttributes)

    // *** End programmer edit section *** (Цех CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ЦехE", new string[] {
            "Адрес as \'Адрес\'",
            "Количество as \'Количество продукции на складе\'"})]
    [AssociatedDetailViewAttribute("ЦехE", "ГотовыйПродукт", "ГотовыйПродуктE", true, "", "Готовый продукт", true, new string[] {
            ""})]
    [View("ЦехL", new string[] {
            "Номер",
            "Адрес",
            "Количество",
            "Описание"})]
    public class Цех : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fАдрес;
        
        private string fОписание;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт fГотовыйПродукт;
        
        // *** Start programmer edit section *** (Цех CustomMembers)

        // *** End programmer edit section *** (Цех CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Цех.Номер CustomAttributes)

        // *** End programmer edit section *** (Цех.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Цех.Номер Get start)

                // *** End programmer edit section *** (Цех.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Цех.Номер Get end)

                // *** End programmer edit section *** (Цех.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Цех.Номер Set start)

                // *** End programmer edit section *** (Цех.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Цех.Номер Set end)

                // *** End programmer edit section *** (Цех.Номер Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Цех.Адрес CustomAttributes)

        // *** End programmer edit section *** (Цех.Адрес CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Цех.Адрес Get start)

                // *** End programmer edit section *** (Цех.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Цех.Адрес Get end)

                // *** End programmer edit section *** (Цех.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Цех.Адрес Set start)

                // *** End programmer edit section *** (Цех.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Цех.Адрес Set end)

                // *** End programmer edit section *** (Цех.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Цех.Описание CustomAttributes)

        // *** End programmer edit section *** (Цех.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Цех.Описание Get start)

                // *** End programmer edit section *** (Цех.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Цех.Описание Get end)

                // *** End programmer edit section *** (Цех.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Цех.Описание Set start)

                // *** End programmer edit section *** (Цех.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Цех.Описание Set end)

                // *** End programmer edit section *** (Цех.Описание Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Цех.Количество CustomAttributes)

        // *** End programmer edit section *** (Цех.Количество CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Цех.Количество Get)
                IDataService ds = DataServiceProvider.DataService;
                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(ГотовыйПродукт), "ГотовыйПродуктE");
                SQLWhereLanguageDef ld = SQLWhereLanguageDef.LanguageDef;

                lcs.LimitFunction = ld.GetFunction(ld.funcEQ,
                    new VariableDef(ld.GuidType, Information.ExtractPropertyPath<ГотовыйПродукт>(x => x.Цех)), this.__PrimaryKey);
                var details = ds.LoadObjects(lcs);
                
                int count = 0;
                for (int i = 0; i < details.Length; i++)
                {
                    count += (int)Information.GetPropValueByName(details[i], "НаСкладе");
                }
                return count;
                // *** End programmer edit section *** (Цех.Количество Get)
            }
            set
            {
                // *** Start programmer edit section *** (Цех.Количество Set)

                // *** End programmer edit section *** (Цех.Количество Set)
            }
        }
        
        /// <summary>
        /// Цех.
        /// </summary>
        // *** Start programmer edit section *** (Цех.ГотовыйПродукт CustomAttributes)

        // *** End programmer edit section *** (Цех.ГотовыйПродукт CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт ГотовыйПродукт
        {
            get
            {
                // *** Start programmer edit section *** (Цех.ГотовыйПродукт Get start)

                // *** End programmer edit section *** (Цех.ГотовыйПродукт Get start)
                if ((this.fГотовыйПродукт == null))
                {
                    this.fГотовыйПродукт = new IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfГотовыйПродукт result = this.fГотовыйПродукт;
                // *** Start programmer edit section *** (Цех.ГотовыйПродукт Get end)

                // *** End programmer edit section *** (Цех.ГотовыйПродукт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Цех.ГотовыйПродукт Set start)

                // *** End programmer edit section *** (Цех.ГотовыйПродукт Set start)
                this.fГотовыйПродукт = value;
                // *** Start programmer edit section *** (Цех.ГотовыйПродукт Set end)

                // *** End programmer edit section *** (Цех.ГотовыйПродукт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЦехE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦехE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦехE", typeof(IIS.АСУ_Кондитерская.Цех));
                }
            }
            
            /// <summary>
            /// "ЦехL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦехL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦехL", typeof(IIS.АСУ_Кондитерская.Цех));
                }
            }
        }
    }
}
