//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чек.
    /// </summary>
    // *** Start programmer edit section *** (Чек CustomAttributes)

    // *** End programmer edit section *** (Чек CustomAttributes)
    [BusinessServer("IIS.АСУ_Кондитерская.ЧекBS, АСУ_Кондитерская.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ЧекE", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Сумма as \'Сумма\'",
            "ИндивидуальныйЗаказ as \'Индивидуальный заказ\'",
            "ИндивидуальныйЗаказ.ФИОЗаказчика as \'ФИО заказчика\'",
            "Продавец as \'Продавец\'",
            "Продавец.Фамилия as \'Фамилия\'",
            "Примечание as \'Примечание\'"}, Hidden=new string[] {
            "ИндивидуальныйЗаказ.ФИОЗаказчика",
            "Продавец.Фамилия"})]
    [AssociatedDetailViewAttribute("ЧекE", "ПозицияВЧеке", "ПозицияВЧекеE", true, "", "Позиция в чеке", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЧекE", "ИндивидуальныйЗаказ", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "ФИОЗаказчика")]
    [MasterViewDefineAttribute("ЧекE", "Продавец", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Фамилия")]
    [View("ЧекL", new string[] {
            "Состояние as \'Состояние\'",
            "Номер as \'Номер\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Сумма as \'Сумма\'",
            "ИндивидуальныйЗаказ.ФИОЗаказчика as \'ФИО заказчика\'",
            "Продавец.Фамилия as \'Продавец\'",
            "Примечание as \'Примечание\'"})]
    public class Чек : IIS.АСУ_Кондитерская.Документ
    {
        
        private IIS.АСУ_Кондитерская.СостояниеЧека fСостояние;
        
        private double fСумма;
        
        private string fПримечание;
        
        private IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ fИндивидуальныйЗаказ;
        
        private IIS.АСУ_Кондитерская.Продавец fПродавец;
        
        private IIS.АСУ_Кондитерская.DetailArrayOfПозицияВЧеке fПозицияВЧеке;
        
        // *** Start programmer edit section *** (Чек CustomMembers)

        // *** End programmer edit section *** (Чек CustomMembers)

        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Состояние CustomAttributes)

        // *** End programmer edit section *** (Чек.Состояние CustomAttributes)
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.СостояниеЧека Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Состояние Get start)

                // *** End programmer edit section *** (Чек.Состояние Get start)
                IIS.АСУ_Кондитерская.СостояниеЧека result = this.fСостояние;
                // *** Start programmer edit section *** (Чек.Состояние Get end)

                // *** End programmer edit section *** (Чек.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Состояние Set start)

                // *** End programmer edit section *** (Чек.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Чек.Состояние Set end)

                // *** End programmer edit section *** (Чек.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Сумма CustomAttributes)

        // *** End programmer edit section *** (Чек.Сумма CustomAttributes)
        [NotNull()]
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Сумма Get start)

                // *** End programmer edit section *** (Чек.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Чек.Сумма Get end)

                // *** End programmer edit section *** (Чек.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Сумма Set start)

                // *** End programmer edit section *** (Чек.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Чек.Сумма Set end)

                // *** End programmer edit section *** (Чек.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Примечание CustomAttributes)

        // *** End programmer edit section *** (Чек.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Примечание Get start)

                // *** End programmer edit section *** (Чек.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (Чек.Примечание Get end)

                // *** End programmer edit section *** (Чек.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Примечание Set start)

                // *** End programmer edit section *** (Чек.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (Чек.Примечание Set end)

                // *** End programmer edit section *** (Чек.Примечание Set end)
            }
        }
        
        /// <summary>
        /// Чек.
        /// </summary>
        // *** Start programmer edit section *** (Чек.ИндивидуальныйЗаказ CustomAttributes)

        // *** End programmer edit section *** (Чек.ИндивидуальныйЗаказ CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ ИндивидуальныйЗаказ
        {
            get
            {
                // *** Start programmer edit section *** (Чек.ИндивидуальныйЗаказ Get start)

                // *** End programmer edit section *** (Чек.ИндивидуальныйЗаказ Get start)
                IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ result = this.fИндивидуальныйЗаказ;
                // *** Start programmer edit section *** (Чек.ИндивидуальныйЗаказ Get end)

                // *** End programmer edit section *** (Чек.ИндивидуальныйЗаказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.ИндивидуальныйЗаказ Set start)

                // *** End programmer edit section *** (Чек.ИндивидуальныйЗаказ Set start)
                this.fИндивидуальныйЗаказ = value;
                // *** Start programmer edit section *** (Чек.ИндивидуальныйЗаказ Set end)

                // *** End programmer edit section *** (Чек.ИндивидуальныйЗаказ Set end)
            }
        }
        
        /// <summary>
        /// Чек.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Продавец CustomAttributes)

        // *** End programmer edit section *** (Чек.Продавец CustomAttributes)
        [PropertyStorage(new string[] {
                "Продавец"})]
        [NotNull()]
        public virtual IIS.АСУ_Кондитерская.Продавец Продавец
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Продавец Get start)

                // *** End programmer edit section *** (Чек.Продавец Get start)
                IIS.АСУ_Кондитерская.Продавец result = this.fПродавец;
                // *** Start programmer edit section *** (Чек.Продавец Get end)

                // *** End programmer edit section *** (Чек.Продавец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Продавец Set start)

                // *** End programmer edit section *** (Чек.Продавец Set start)
                this.fПродавец = value;
                // *** Start programmer edit section *** (Чек.Продавец Set end)

                // *** End programmer edit section *** (Чек.Продавец Set end)
            }
        }
        
        /// <summary>
        /// Чек.
        /// </summary>
        // *** Start programmer edit section *** (Чек.ПозицияВЧеке CustomAttributes)

        // *** End programmer edit section *** (Чек.ПозицияВЧеке CustomAttributes)
        public virtual IIS.АСУ_Кондитерская.DetailArrayOfПозицияВЧеке ПозицияВЧеке
        {
            get
            {
                // *** Start programmer edit section *** (Чек.ПозицияВЧеке Get start)

                // *** End programmer edit section *** (Чек.ПозицияВЧеке Get start)
                if ((this.fПозицияВЧеке == null))
                {
                    this.fПозицияВЧеке = new IIS.АСУ_Кондитерская.DetailArrayOfПозицияВЧеке(this);
                }
                IIS.АСУ_Кондитерская.DetailArrayOfПозицияВЧеке result = this.fПозицияВЧеке;
                // *** Start programmer edit section *** (Чек.ПозицияВЧеке Get end)

                // *** End programmer edit section *** (Чек.ПозицияВЧеке Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.ПозицияВЧеке Set start)

                // *** End programmer edit section *** (Чек.ПозицияВЧеке Set start)
                this.fПозицияВЧеке = value;
                // *** Start programmer edit section *** (Чек.ПозицияВЧеке Set end)

                // *** End programmer edit section *** (Чек.ПозицияВЧеке Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧекE", typeof(IIS.АСУ_Кондитерская.Чек));
                }
            }
            
            /// <summary>
            /// "ЧекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧекL", typeof(IIS.АСУ_Кондитерская.Чек));
                }
            }
        }
    }
}
