/*flexberryautogenerated="false"*/
namespace IIS.АСУ_Кондитерская
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ПродуктL : BaseListForm<Продукт>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ПродуктL() : base(Продукт.Views.ПродуктL)
        {
            EditPage = ПродуктE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Produkt/ProduktL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
            IDataService ds = DataServiceProvider.DataService;
            var dobjs = ds.LoadObjects(Продукт.Views.ПродуктL);
            
            int count = 0;
            double price = 0;
            foreach (Продукт prod in dobjs)
                {
                    count++;
                    price += prod.Цена / prod.Масса;
                }
            double result = 1000 * price / count;
            descAverPrice.Text = result.ToString();            
        }
    }
}
