//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ГотовыйПродуктBS.
    /// </summary>
    // *** Start programmer edit section *** (ГотовыйПродуктBS CustomAttributes)

    // *** End programmer edit section *** (ГотовыйПродуктBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ГотовыйПродуктBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ГотовыйПродуктBS CustomMembers)

        // *** End programmer edit section *** (ГотовыйПродуктBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateГотовыйПродукт CustomAttributes)

        // *** End programmer edit section *** (OnUpdateГотовыйПродукт CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateГотовыйПродукт(IIS.АСУ_Кондитерская.ГотовыйПродукт UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateГотовыйПродукт)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateГотовыйПродукт)
        }
    }
}
