//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ИндЗаказBS.
    /// </summary>
    // *** Start programmer edit section *** (ИндЗаказBS CustomAttributes)

    // *** End programmer edit section *** (ИндЗаказBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ИндЗаказBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ИндЗаказBS CustomMembers)

        // *** End programmer edit section *** (ИндЗаказBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateИндивидуальныйЗаказ CustomAttributes)

        // *** End programmer edit section *** (OnUpdateИндивидуальныйЗаказ CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateИндивидуальныйЗаказ(IIS.АСУ_Кондитерская.ИндивидуальныйЗаказ UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateИндивидуальныйЗаказ)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateИндивидуальныйЗаказ)
        }
    }
}
