//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Кондитерская
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЧекBS.
    /// </summary>
    // *** Start programmer edit section *** (ЧекBS CustomAttributes)

    // *** End programmer edit section *** (ЧекBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЧекBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ЧекBS CustomMembers)

        // *** End programmer edit section *** (ЧекBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateЧек CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЧек CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЧек(IIS.АСУ_Кондитерская.Чек UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЧек)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateЧек)
        }
    }
}
